sass:
  sass_dir: assets/css

baseurl: https://seinwave.github.io/msdev/

collections:
 authors:
  output: true
  
  defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"